export * from './common'
export * as AuthActionType from './modules/auth'
export * as OrdersActionType from './modules/orders'
export * as GamesActionType from './modules/games'
export * as TestActionType from './modules/test'
